version: '3.8'

services:
  app:
    build: ./
    container_name: my_app
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: my_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
